hard_tabs = true
use_small_heuristics = "Max"
max_width = 100
comment_width = 100
chain_width = 80
imports_granularity = "Crate"
spaces_around_ranges = true
binop_separator = "Back"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
